# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0003_auto_20171214_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='GiveOffer',
        ),
    ]
