# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0005_auto_20171218_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoffer',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnt.Profile'),
        ),
    ]
