# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0006_auto_20171219_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoffer',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
