# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 11:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnt', '0012_auto_20171219_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoffer',
            name='pickup_timeslots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(max_length=200), size=None),
        ),
    ]
